#!/usr/bin/env bash

if [[ $# -le 1 ]]
  then
  echo ""
  echo "Usage $0 path/to/file.feature..."
  echo ""
  exit 1
fi

if [[ ! -d ~/.f2j ]]
  then
  mkdir ~/.f2j
fi

for file in ${@}
do
  base=$(basename $file)
  name=${base%.*}
  ext=${base##*.}

  if [[ $ext == "feature" && -f $file ]]
    then
    cp $file ~/.f2j/$file
    sed "{
      /^\(@.*\)$/s//{color:blue}\1{color}/g
      /^\(Scenario\)/s//{color:red}_\1_{color}/g
      /^\(Feature\)/s//{color:red}_\1_{color}/g
      /^\([ ]\{2,\}\)\(Given\)/s//*\1{color:red}*\2*{color}/g
      /^\([ ]\{2,\}\)\(And\)/s//*\1{color:red}*\2*{color}/g
      /^\([ ]\{2,\}\)\(When\)/s//*\1{color:red}*\2*{color}/g
      /^\([ ]\{2,\}\)\(Then\)/s//*\1{color:red}*\2*{color}/g
      /^\([ ]\{2,\}\)\(As\)/s//*\1{color:red}*\2*{color}/g
      /^\([ ]\{2,\}\)\(I\)/s//*\1{color:red}*\2*{color}/g
      /^\([ ]\{2,\}\)\(So\)/s//*\1{color:red}*\2*{color}/g
      /\([a-zA-Z0-9\{\}\-_\+] \)\(\"[^\"]\{1,\}\"\)/s//\1{color:orange}\2{color}/g
      /^\*.*$/,/^\([ ]\{2,\}\)\(\"\"\"\)/{
        /^\([ ]\{2,\}\)\(\"\"\"\)/s//{quote}\1{color:orange}\2/
      }
      /^\([ ]\{2,\}\)\(\"\"\"\)/s//\1\2{color}{quote}/
    }" $file > ~/.f2j/$file
    cat ~/.f2j/$file
    rm ~/.f2j/$file
  else
    echo "Could not do anything with $file because it either doesn't exist or is not a .feature file"
  fi
done
